### ISSUE TITLE
Support of safe environment deletion

### ISSUE THREAD

**Issue by Kerollmops** [Kerollmops/heed#58]
There is a fondamental API that heed must support for the new MeiliSearch engine to be able to support index deletion, the [`mdb_env_close`](http://www.lmdb.tech/doc/group__mdb.html#ga4366c43ada8874588b6a62fbda2d1e95).

This function deletes a given environment, after an environment is safely closed it is possible to safely delete it from disk too.

The problem with this function call is that the API user must ensure that no transaction are still alive, but there is no way to ensure that by ourself as the transactions mutexes are handle by LMDB itself, the only way would be to redefine the mutex logic ourselves.

And this why this issue is here, defining the mutex logic in heed and disable the LMDB one (only if a feature is enabled).

I took a look a the best library for synchronization primitives in Rust, [parking_lot](https://docs.rs/parking_lot) and the conclusion is that we should use a [Mutex](https://docs.rs/parking_lot/0.11.0/parking_lot/type.Mutex.html) for write transactions and a [RwLock](https://docs.rs/parking_lot/0.11.0/parking_lot/type.RwLock.html) for read-only transactions.

Thanks to the RwLock we are able to block readers by write-locking it, avoiding readers to acquire read transactions, this will allow heed to ensure that it got exclusive access either for the write and the read part, allowing it to safely delete the environment or any other operation that require exclusively access.

There is one little missing problem: ensuring that the db handle is not used again by the library user. Maybe trying to lock a deleted db should return a specific error, informing the library user that this db handle is invalid.

To enable the user-end locking feature we must first disable the inerrant locking system of LDMB, we can do so by enabling the `NO_LOCK` flag when opening an environment.

However, I am not sure about the description of the `NO_LOCK` parameter of the [`mdb_env_open`](http://www.lmdb.tech/doc/group__mdb.html#ga32a193c6bf4d7d5c5d579e71f22e9340) flag.

> For proper operation the caller must enforce single-writer semantics, and must ensure that no readers are using old transactions while a writer is active. The simplest approach is to use an exclusive lock so that no readers may be active at all when a writer begins.

Does it mean that it is not possible to have concurrent readers and writers when the `NO_LOCK` flag is set?

**Comment by erthink** [comment]
I don't think you should use `NO_LOCK`. Because in this case, you need to completely repeat the locking scheme (which is not easy), or give up some features (lock-free for readers and/or access from other processes, hot backup etc). This is the reason why I removed support of `NO_LOCK` from [libmdbx](https://github.com/erthink/libmdbx).

The [KISS-way](https://en.wikipedia.org/wiki/KISS_principle): just remove file, starting from `dat` file  and then `clk`.
  - On Windows you will get share violation error if any process still use the environment.
  - On POSIX systems, processes already working with the database will continue to work without interference until it close the environment.

More for On POSIX systems:
If before deleting, you need to make sure that there are no processes working with the environment, but in libmdbx you should try to open it with the [`MDBX_EXCLUSIVE`](https://erthink.github.io/libmdbx/group__c__opening.html#gga9138119a904355d245777c4119534061aa516c74e6fed22c9812bb909c8c459ed) flag. In the case of LMDB you should start write transaction and acquire advisory lock by `fcntl()` on the lck-file in range of `0`..`PID_MAX` (it will be successful if there are no readers).

P.S.
I'll probably add `mdbx_env_delete()` today for this purpose.

**Comment by Kerollmops** [comment]
Thank you very much @erthink for the help on this subject, [heed supports a safe way of closing an environment](https://github.com/Kerollmops/heed/pull/64) by ensuring that transactions don't live longer than the env they were created from (obviously using the Rust lifetimes), this way we are sure that it is impossible to close an environment that has open transactions.
